sudo: required
language: android
jdk: oraclejdk8
dist: trusty

# Install Android SDK
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository

before_install:
  # Hack to accept Android licenses
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"
  # Install protobuf compiler
  - sudo apt-get install protobuf-compiler
  # Install syncthing-java manually, as the current commit may require a development version.
  - git clone https://github.com/Nutomic/syncthing-java.git
  - cd "syncthing-java"
  - gradle install
  - cd ..

# Cache gradle dependencies
# https://docs.travis-ci.com/user/languages/android/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew lint
  - ./gradlew assembleDebug
